version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/test-stack
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
